site_name: Nicolas GORALSKI docs
plugins:
    - search
theme:
    name: material
nav:
  - Home: 'combine.md'
  - Softs: 'softs.md'
  - IT:
      - freeipa: 'IT/freeipa.md'
      - Linux Best Practices: 'IT/linux-best-practices.md'
      - Bookmarks: 'IT/bookmarks.md'      
      - Python Tips \& Tricks: 'IT/python_tipstricks.md'      
  - Domotic:
      - Tasmota: ''
      - Domoticz: 'domoticz/combine.md'

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
